language: python
python:
  - 2.7
  - 3.3
sudo: false

notifications:
  slack: lisvai:SgdQxglgGWYCyiAAWa3aU5Pg

# Skeleton from https://gist.github.com/dan-blanchard/7045057
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  # Trying to suppress sudo for migrating to container-based infra
  # - sudo rm -rf /dev/shm
  # - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION nose numpy scipy scikit-learn
  # Coverage packages are on my binstar channel
  - conda install --yes -c dan_blanchard python-coveralls nose-cov

# Run test
script:
  - nosetests --with-coverage --cover-package simple_esn.py --logging-level=INFO
# suppressed nosetests --with-cov --cover-package simple_esn --cov-config .coveragerc  --logging-level=INFO

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc


# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
#script: nosetests
